# Generated by Django 2.0.13 on 2019-07-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190727_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='button',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
